apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    name: redis-slave
spec:
  type: NodePort
  ports:
  - port: 6379
  selector:
    name: redis-slave
---
apiVersion: v1
kind: ReplicationController
metadata:
  name namenameameeis-slave
spec:
  replicas: 2
  selector:
    name: ave
  template:
    metadata:
      name: redis-slave
      labels:
        name: redis-slave
    spec:
      containers:
      - name: redis-slave
        image: kubeguide/guestbook-redis-slave
        env:
        - name: GET_HOSTS_FROM
          value: redis-master
        ports:
        - containerPort: 6379
