apiVersion: v1
kind: Service
metadata:
  name: ku8-redis-master
spec:
  ports:
    - port: 6379
  selector:
    app: ku8-redis-master
---
apiVersion: v1
kind: Pod
metadata:
  name: ku8-redis-master
  labels:
       app: ku8-redis-master
spec:
      containers:
        - name: server
          image: redis
          ports:
            - containerPort: 6379
      restartPolicy: Never   
