apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster1
  labels:
    app: kafka-cluster-1
spec:
  type: NodePort
  ports:
  - port: 9092
    name: kafka-cluster-1
    targetPort: 9092
    nodePort: 30091
    protocol: TCP
  selector:
    app: kafka-cluster-1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster2
  labels:
    app: kafka-cluster-2
spec:
  type: NodePort
  ports:
  - port: 9092
    name: kafka-cluster-2
    targetPort: 9092
    nodePort: 30092
    protocol: TCP
  selector:
    app: kafka-cluster-2
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster3
  labels:
    app: kafka-cluster-3
spec:
  type: NodePort
  ports:
  - port: 9092
    name: kafka-cluster-3
    targetPort: 9092
    nodePort: 30093
    protocol: TCP
  selector:
    app: kafka-cluster-3