kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-cluster-1 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-cluster-1 
  template:
    metadata:
      labels:
        name: kafka-cluster-1
        app: kafka-cluster-1
    spec:
      containers:
      - name: kafka-cluster-1
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "zookeeper-cluster1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-cluster1:2181,zookeeper-cluster2:2181,zookeeper-cluster3:2181
        - name: KAFKA_BROKER_ID
          value: "1"
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-cluster-2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-cluster-2
  template:
    metadata:
      labels:
        name: kafka-cluster-2
        app: kafka-cluster-2
    spec:
      containers:
      - name: kafka-cluster-2
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "zookeeper-cluster2"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-cluster1:2181,zookeeper-cluster2:2181,zookeeper-cluster3:2181
        - name: KAFKA_BROKER_ID
          value: "2"
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-cluster-3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-cluster-3
  template:
    metadata:
      labels:
        name: kafka-cluster-3
        app: kafka-cluster-3
    spec:
      containers:
      - name: kafka-cluster-3
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "zookeeper-cluster3"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-cluster1:2181,zookeeper-cluster2:2181,zookeeper-cluster3:2181
        - name: KAFKA_BROKER_ID
          value: "3"