apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-cluster-service-1
  name: zookeeper-cluster1
spec:
  ports:
  - name: client 
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper-cluster-service-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-cluster-service-2
  name: zookeeper-cluster2
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper-cluster-service-2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-cluster-service-3
  name: zookeeper-cluster3
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper-cluster-service-3