kind: Service
apiVersion: v1
metadata:
  name: my-nginx
spec:
  type: NodePort
  ports:
    - port: 80
    targetPort: 80
    nodePort: 31000 # nodePort 值的默认范围是 30000-32767
  selector:
    name: my-nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    name: my-nginx
spec:
  containers:
    - name: my-nginx
    image: nginx:1.7.9
    ports:
      - containerPort: 80