# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-claim
#   annotations:
#     volume.beta.kubernetes.io/storage-class: "default"
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-claim
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi