apiVersion: v1
kind: Service
metadata:
  name: demo2-svc
  labels:
    app: demob
spec:
  ports:
    - port: 8080
  selector:
    app: demob
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: demo2-dep
  labels:
    app: demob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demob
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demob
        tier: frontend
    spec:
      containers:
      - image: liam1803/mb-gotest:0.0.5
        name: demob
        env:
        - name: SERVER_DB_HOST
          value: demo1-dep
        ports:
        - containerPort: 8080
          name: demob


